baseURL: "https://pingryte.com/"
title: Pingryte
copyright: "© Pingryte"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Posts
          url: /posts/
          weight: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Pingryte – Tech, tools, and automation without the fluff."
  author: "Pingryte"
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["images/papermod-cover.png"]
  footer:
    disable: true


  homeInfoParams:
    Title: "Welcome to Pingryte"
    Content: >
      Tech, tools, and automation — without the fluff.

  socialIcons:
    - name: github
      title: GitHub
      url: "https://github.com/pingryte"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
